$(function(){function n(b,e){var f=function(){};f.prototype=e.prototype;b.prototype=new f;b.prototype.constructor=b;b["super"]=e}function l(b,e){var f=$("table#alrt_table"),d;d=""+('<tr id="alrt_'+b+'">')+"<td>";d+='<select id="cb_alrt_type_'+b+'">';d+='<option value="null" selected disabled>TYPE</option>';d+='<option value="price">Price</option>';d+='<option value="arbitrage">Arbitrage</option>';d+="</select>";d+="</td>";d+='<td id="row_alrt_'+b+'">select an alert type</td>';d+="</tr>";f.append(d);
null!=e&&$("select#cb_alrt_type_"+b+' option[value="'+e+'"]').prop("selected",!0);$("select#cb_alrt_type_"+b).on("change",function(){(new h[this.value](b)).makeUI()})}function m(b,e){if(void 0!==windows[b])return windowShow(b),!1;var f=$("div#markets_page"),d="Alert";"alerts"==b&&(d="Markets - Alerts");f.append('<div class="winbc" id="win_'+b+'"> <div class="winbar" id="winbar_'+b+'"> <span id="win_title_'+b+'" class="winbar_title">'+d+'</span><span class="winbar_ctrl"><a id="ctred_'+b+'" class="winctrl" href="#">-</a> <a id="ct_'+
b+'" class="winctrl" href="#">x</a></span><br /></div><br/><div class="winbc_ctnt" id="win_ctnt_'+b+'" style="font-size:85%;"><div class="winbc_inctnt" id="win_inctnt_'+b+'"></div><br/></div><div class="winclosebtn" id="win_cl_'+b+'"><a id="ct_'+b+'" class="winctrl" href="#">&nbsp;Close&nbsp;</a></div></div>');f=$("div#win_"+b);f.css("transform","translate(320px,"+.2*$("body").height()+"px)");windowUI(f,$("div#winbar_"+b));e&&(f.slideToggle(),windowRaise(f));$("a#ct_"+b).click(function(e){e.preventDefault();
windowToggle(b)});$("a#ctred_"+b).click(function(e){e.preventDefault();windowReduce(b)});windows[b]=f;return!0}function k(){var b={};for(a in alerts)b[a]=alerts[a].getConfig();var e=new Date;e.setDate(e.getDate()+366);document.cookie="alerts="+JSON.stringify(b)+"; expires="+e.toUTCString()}var g=null,p=function(){return function(b){this.aid=b;this.audio_iter=0;this.locked=!1;this.setConfig=function(b){b.hasOwnProperty("locked")&&(this.locked=b.locked)};this.getConfig=function(){var b={};b.type=this.constructor.getName();
b.locked=this.locked;return b};this.startAudio=function(){null!=g&&3>this.audio_iter&&g.paused&&(this.audio_iter+=1,g.play())};this.makeUI=function(){var b=this,f=$("td#row_alrt_"+this.aid),d;d="&nbsp; "+('<button id="btn_alrt_edit_'+this.aid+'">on</button>&nbsp;');d+='<button id="btn_alrt_'+this.aid+'">add</button>';f.append(d);$("button#btn_alrt_"+this.aid).button();$("button#btn_alrt_"+this.aid).button("option","icons",{primary:"ui-icon-circle-plus"});$("button#btn_alrt_"+this.aid).on("click",
function(){b.lock()&&(b.add(),alerts[b.aid]=b,++nb_alerts,k(),l(nb_alerts,null))});$("button#btn_alrt_edit_"+this.aid).button({disabled:!0});$("button#btn_alrt_edit_"+this.aid).button("option","icons",{primary:"ui-icon-locked"})};this.lock=function(){var b=this;this.locked=!0;this.audio_iter=0;$("button#btn_alrt_edit_"+this.aid).button("option","label","on");$("button#btn_alrt_edit_"+this.aid).button("option","icons",{primary:"ui-icon-locked"});$("button#btn_alrt_edit_"+this.aid).off();$("button#btn_alrt_edit_"+
this.aid).on("click",function(){b.unlock()});$("select#cb_alrt_type_"+this.aid).attr("disabled","true");k();return!0};this.unlock=function(){var b=this;this.locked=!1;$("button#btn_alrt_edit_"+this.aid).button("option","label","off");$("button#btn_alrt_edit_"+this.aid).button("option","icons",{primary:"ui-icon-unlocked"});$("button#btn_alrt_edit_"+this.aid).off();$("button#btn_alrt_edit_"+this.aid).on("click",function(){b.lock()});$("select#cb_alrt_type_"+this.aid).removeAttr("disabled");k()};this.add=
function(){var b=this;$("button#btn_alrt_"+this.aid).button("option","label","delete");$("button#btn_alrt_"+this.aid).button("option","icons",{primary:"ui-icon-circle-minus"});$("button#btn_alrt_"+this.aid).off();$("button#btn_alrt_"+this.aid).on("click",function(){b.remove()});$("button#btn_alrt_edit_"+this.aid).button("enable")};this.remove=function(){$("button#btn_alrt_"+this.aid).off();$("tr#alrt_"+this.aid).remove();delete alerts[this.aid];k()};this.destroy=function(){}}}(),q=function(){var b=
function(b){this.constructor["super"].call(this,b);this.cond=this.exchange=null;this.price=0;var f=this.setConfig;this.setConfig=function(b){f.call(this,b);b.hasOwnProperty("exch")&&(this.exchange=b.exch);b.hasOwnProperty("cond")&&(this.cond=b.cond);b.hasOwnProperty("price")&&(this.price=b.price)};var d=this.getConfig;this.getConfig=function(){var b=d.call(this);b.exch=this.exchange;b.cond=this.cond;b.price=this.price;return b};var g=this.makeUI;this.makeUI=function(){var b=this,d=$("td#row_alrt_"+
this.aid);d.empty();var c;c=""+('<select id="cb_alrt_exch_'+this.aid+'">');c+='<option value="null" selected disabled>EXCHANGE</option>';for(var e in exchanges_info){var f=exchanges_info[e];c+='<option value="'+f.name+'" id="alrt_exch_'+f.name+'">'+f.name+"</option>"}c+="</select>&nbsp; ";c+='<select id="cb_alrt_cond_'+this.aid+'">';c+='<option value="null" selected disabled>CONDITION</option>';c+='<option value="gt" id="alrt_cond_gt">above</option>';c+='<option value="lt" id="alrt_cond_gt">below</option>';
c+="</select>";c+="&nbsp; ";c+='<input type="text" name="s" id="alrt_value_'+this.aid+'" value="'+this.price+'" maxlength="8" size="5"/> ';c+='<span id="alrt_cur_'+this.aid+'">'+(null!=this.exchange?getExchangeCurrency(this.exchange):"USD")+"</span>";d.append(c);null!=this.exchange&&$("select#cb_alrt_exch_"+this.aid+' option[value="'+this.exchange+'"]').prop("selected",!0);null!=this.cond&&$("select#cb_alrt_cond_"+this.aid+' option[value="'+this.cond+'"]').prop("selected",!0);$("select#cb_alrt_exch_"+
this.aid).on("change",function(){$("span#alrt_cur_"+b.aid).text(getExchangeCurrency(this.value))});g.call(this)};var h=this.lock;this.lock=function(){var b=$("select#cb_alrt_exch_"+this.aid).val(),d=$("select#cb_alrt_cond_"+this.aid).val(),c=parseFloat($("input#alrt_value_"+this.aid).val());if(null==b||null==d||0>=c||isNaN(c))return!1;this.exchange=b;this.cond=d;this.price=c;$("select#cb_alrt_exch_"+this.aid).attr("disabled","true");$("select#cb_alrt_cond_"+this.aid).attr("disabled","true");$("input#alrt_value_"+
this.aid).attr("disabled","true");return h.call(this)};var k=this.unlock;this.unlock=function(){$("select#cb_alrt_exch_"+this.aid).removeAttr("disabled");$("select#cb_alrt_cond_"+this.aid).removeAttr("disabled");$("input#alrt_value_"+this.aid).removeAttr("disabled");k.call(this)};this.trigger=function(b){m("alrt_"+this.aid,!0);var d=$("div#win_inctnt_alrt_"+this.aid);d.empty();var c="",e=getExchangeCurrency(this.exchange),c=c+("Exchange "+this.exchange+" is "+("lt"==this.cond?"below":"above")+" "+
this.price+" "+e+".<br/>");d.append(c+("Current Price : "+b+" "+e));this.startAudio()};this.tick=function(b){if(this.locked&&b.hasOwnProperty(this.exchange)){var d=!1;b=b[this.exchange];"gt"==this.cond?b.last>this.price&&(d=!0):"lt"==this.cond&&b.last<this.price&&(d=!0);d?this.trigger(b.last):this.audio_iter=0}};var l=this.remove;this.remove=function(){$("select#cb_alrt_exch_"+this.aid).off();l.call(this)}};n(b,p);b.getName=function(){return"price"};b.getTitle=function(){return"Price"};return b}(),
r=function(){var b=function(b){this.constructor["super"].call(this,b);this.exchange2=this.exchange1=null;this.cst2=this.fees2=this.fees1=0;var f=this.setConfig;this.setConfig=function(b){f.call(this,b);b.hasOwnProperty("exch1")&&(this.exchange1=b.exch1);b.hasOwnProperty("fees1")&&(this.fees1=b.fees1);b.hasOwnProperty("exch2")&&(this.exchange2=b.exch2);b.hasOwnProperty("fees2")&&(this.fees2=b.fees2);b.hasOwnProperty("cst2")&&(this.cst2=b.cst2)};var d=this.getConfig;this.getConfig=function(){var b=
d.call(this);b.exch1=this.exchange1;b.fees1=this.fees1;b.exch2=this.exchange2;b.fees2=this.fees2;b.cst2=this.cst2;return b};var g=this.makeUI;this.makeUI=function(){var b=this,d=$("td#row_alrt_"+this.aid);d.empty();var c;c=""+('<select id="cb_alrt_exch1_'+this.aid+'">');c+='<option value="null" selected disabled>EXCHANGE</option>';for(var e in exchanges_info){var f=exchanges_info[e];c+='<option value="'+f.name+'">'+f.name+"</option>"}c=c+"</select>"+(' Bid + <input type="text" name="s" id="alrt_fees1_'+
this.aid+'" value="'+this.fees1+'" maxlength="6" size="3"/>%');c+=" &nbsp; <b>&gt;</b> ";c+="&nbsp; ";c+='<select id="cb_alrt_exch2_'+this.aid+'">';c+='<option value="null" selected disabled>EXCHANGE</option>';for(e in exchanges_info)f=exchanges_info[e],c+='<option value="'+f.name+'">'+f.name+"</option>";c+="</select>";c+=' Ask + <input type="text" name="s" id="alrt_fees2_'+this.aid+'" value="'+this.fees2+'" maxlength="6" size="3"/>%';c+=' + <input type="text" name="s" id="alrt_cst2_'+this.aid+'" value="'+
this.cst2+'" maxlength="6" size="3"/> ';c+='<span id="alrt_cur_'+this.aid+'">'+(null!=this.exchange2?getExchangeCurrency(this.exchange2):"USD")+"</span>";d.append(c);null!=this.exchange1&&$("select#cb_alrt_exch1_"+this.aid+' option[value="'+this.exchange1+'"]').prop("selected",!0);null!=this.exchange2&&$("select#cb_alrt_exch2_"+this.aid+' option[value="'+this.exchange2+'"]').prop("selected",!0);$("select#cb_alrt_exch2_"+this.aid).on("change",function(){$("span#alrt_cur_"+b.aid).text(getExchangeCurrency(this.value))});
g.call(this)};var h=this.lock;this.lock=function(){var b=$("select#cb_alrt_exch1_"+this.aid).val(),d=parseFloat($("input#alrt_fees1_"+this.aid).val()),c=$("select#cb_alrt_exch2_"+this.aid).val(),e=parseFloat($("input#alrt_fees2_"+this.aid).val()),f=parseFloat($("input#alrt_cst2_"+this.aid).val());if(null==b||null==c||isNaN(d)||isNaN(e)||isNaN(f))return!1;this.exchange1=b;this.fees1=d;this.exchange2=c;this.fees2=e;this.cst2=f;$("select#cb_alrt_exch1_"+this.aid).attr("disabled","true");$("input#alrt_fees1_"+
this.aid).attr("disabled","true");$("select#cb_alrt_exch2_"+this.aid).attr("disabled","true");$("input#alrt_fees2_"+this.aid).attr("disabled","true");$("input#alrt_cst2_"+this.aid).attr("disabled","true");return h.call(this)};var k=this.unlock;this.unlock=function(){$("select#cb_alrt_exch1_"+this.aid).removeAttr("disabled");$("input#alrt_fees1_"+this.aid).removeAttr("disabled");$("select#cb_alrt_exch2_"+this.aid).removeAttr("disabled");$("input#alrt_fees2_"+this.aid).removeAttr("disabled");$("input#alrt_cst2_"+
this.aid).removeAttr("disabled");k.call(this)};this.trigger=function(b,d){m("alrt_"+this.aid,!0);var c=$("div#win_inctnt_alrt_"+this.aid);c.empty();var e="",f=getExchangeCurrency(this.exchange1),g=getExchangeCurrency(this.exchange2),e=e+(this.exchange1+" bid is above "+this.exchange2+" ask.<br/><br/>"),e=e+("&nbsp; ("+b+" "+f+" + "+this.fees1+"%) <b>&gt;</b> ("),e=e+(d+" "+g+" + "+this.fees2+"%");0!=this.cst2&&(e+=" + "+this.cst2+" "+g);c.append(e+")");this.startAudio()};this.tick=function(b){if(this.locked){var d=
0,c=0,e=0;if(b.hasOwnProperty(this.exchange1)&&b.hasOwnProperty(this.exchange2)){var f=b[this.exchange1];b=b[this.exchange2];d=f.bid*f.rusd;c=b.ask*b.rusd;e=this.cst2*b.rusd;d*(1+this.fees1/100)>c*(1+this.fees2/100)+e?this.trigger(f.bid,b.ask):this.audio_iter=0}}};var l=this.remove;this.remove=function(){l.call(this)}};n(b,p);b.getName=function(){return"arbitrage"};b.getTitle=function(){return"Arbitrage"};return b}(),h={};h[q.getName()]=q;h[r.getName()]=r;m("alerts",!1);$("div#win_inctnt_alerts").empty();
$("div#win_inctnt_alerts").append('<table id="alrt_table" class="chain_txs_table"></table><br/>note: alerts are saved using cookies, data aren\'t sent to the server<br/>');(function(){var b=document.cookie,e=b.indexOf("alerts=");if(-1!=e){var e=b.indexOf("=",e)+1,f=b.indexOf(";",e),b=-1!=f?unescape(b.substring(e,f)):unescape(b.substring(e)),d;try{d=JSON.parse(b)}catch(g){return}for(aid in d)b=d[aid].type,b in h&&(l(aid,b),b=new h[b](aid),b.setConfig(d[aid]),b.makeUI(),b.add(),alerts[b.aid]=b,b.locked?
b.lock():b.unlock(),nb_alerts=Math.max(nb_alerts,aid)+1)}})();l(nb_alerts,null);$("a#ct_markets_alerts").on("click",function(b){b.preventDefault();windowToggle("alerts");null==g&&(g=new Audio,g.canPlayType("audio/ogg")?g=new Audio("/coinorama/static/alert.ogg"):g.canPlayType("audio/mp3")&&(g=new Audio("/coinorama/static/alert.mp3")),g.load())})});
